import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import Sidebar from "@/components/ui/sidebar";
import { createClient } from "@/lib/supabase/server";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const supabase = createClient();
  const { data, error } = await supabase.from("posts").select("slug, id");
  if (error) {
    console.error(error);
  }

  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          inter.variable,
        )}
      >
        <div className="flex w-screen h-screen">
          <Sidebar
            contents={data?.map((post) => ({
              slug: post.slug,
              href: `/${post.slug}`,
              activated: true,
              label: post.slug,
            }))}
          />
          <main className="px-8 py-4 w-5/6 h-full">{children}</main>
          <footer></footer>
        </div>
      </body>
    </html>
  );
}
